/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module spi(clk, rst, ss, mosi, miso, sck, done, din, dout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire [2:0] _107_;
  wire [2:0] _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire [2:0] bit_ct_q;
  input clk;
  wire clk;
  wire [7:0] data_d;
  wire [7:0] data_q;
  input [7:0] din;
  wire [7:0] din;
  output done;
  wire done;
  wire done_q;
  output [7:0] dout;
  wire [7:0] dout;
  wire [7:0] dout_q;
  output miso;
  wire miso;
  wire miso_d;
  wire miso_q;
  input mosi;
  wire mosi;
  wire mosi_d;
  wire mosi_q;
  input rst;
  wire rst;
  input sck;
  wire sck;
  wire sck_d;
  wire sck_old_d;
  wire sck_old_q;
  wire sck_q;
  input ss;
  wire ss;
  wire ss_d;
  wire ss_q;
  sky130_fd_sc_hd__clkinv_1 _134_ (
    .A(_071_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _135_ (
    .A(_038_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(_106_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(_103_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _138_ (
    .A(_105_),
    .SLEEP(_104_),
    .X(_082_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _139_ (
    .A(_106_),
    .SLEEP(_082_),
    .X(_022_)
  );
  sky130_fd_sc_hd__a31oi_1 _140_ (
    .A1(_038_),
    .A2(_037_),
    .A3(_036_),
    .B1(_106_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(_055_),
    .A1(_072_),
    .S(_083_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(_056_),
    .A1(_047_),
    .S(_083_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(_057_),
    .A1(_048_),
    .S(_083_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(_058_),
    .A1(_049_),
    .S(_083_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(_059_),
    .A1(_050_),
    .S(_083_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(_060_),
    .A1(_051_),
    .S(_083_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(_061_),
    .A1(_052_),
    .S(_083_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _148_ (
    .A0(_062_),
    .A1(_053_),
    .S(_083_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and4b_1 _149_ (
    .A_N(_104_),
    .B(_105_),
    .C(_036_),
    .D(_037_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nand4b_1 _150_ (
    .A_N(_104_),
    .B(_105_),
    .C(_036_),
    .D(_037_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_038_),
    .B(_084_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor3_1 _152_ (
    .A(_106_),
    .B(_103_),
    .C(_086_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o211ai_1 _153_ (
    .A1(_036_),
    .A2(_082_),
    .B1(_081_),
    .C1(_080_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _154_ (
    .A1(_036_),
    .A2(_082_),
    .B1(_087_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21oi_1 _155_ (
    .A1(_036_),
    .A2(_082_),
    .B1(_037_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor4_1 _156_ (
    .A(_106_),
    .B(_103_),
    .C(_084_),
    .D(_088_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(_079_),
    .B(_085_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__and4_1 _158_ (
    .A(_080_),
    .B(_081_),
    .C(_086_),
    .D(_089_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a31oi_1 _159_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_063_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor4_1 _160_ (
    .A(_072_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor3_1 _161_ (
    .A(_103_),
    .B(_090_),
    .C(_091_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a31oi_1 _162_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_064_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor4_1 _163_ (
    .A(_047_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor3_1 _164_ (
    .A(_103_),
    .B(_092_),
    .C(_093_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a31oi_1 _165_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_065_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor4_1 _166_ (
    .A(_048_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor3_1 _167_ (
    .A(_103_),
    .B(_094_),
    .C(_095_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a31oi_1 _168_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_066_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor4_1 _169_ (
    .A(_049_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor3_1 _170_ (
    .A(_103_),
    .B(_096_),
    .C(_097_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a31oi_1 _171_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_067_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor4_1 _172_ (
    .A(_050_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor3_1 _173_ (
    .A(_103_),
    .B(_098_),
    .C(_099_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a31oi_1 _174_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_068_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4_1 _175_ (
    .A(_051_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor3_1 _176_ (
    .A(_103_),
    .B(_100_),
    .C(_101_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a31oi_1 _177_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_069_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor4_1 _178_ (
    .A(_052_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor3_1 _179_ (
    .A(_103_),
    .B(_102_),
    .C(_073_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a31oi_1 _180_ (
    .A1(_038_),
    .A2(_080_),
    .A3(_084_),
    .B1(_070_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor4_1 _181_ (
    .A(_053_),
    .B(_079_),
    .C(_106_),
    .D(_085_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor3_1 _182_ (
    .A(_103_),
    .B(_074_),
    .C(_075_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _183_ (
    .A(_104_),
    .SLEEP(_105_),
    .X(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _184_ (
    .A1(_106_),
    .A2(_076_),
    .B1(_054_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o311ai_0 _185_ (
    .A1(_078_),
    .A2(_106_),
    .A3(_076_),
    .B1(_077_),
    .C1(_081_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__dfxtp_1 _186_ (
    .CLK(clk),
    .D(_109_),
    .Q(done_q)
  );
  sky130_fd_sc_hd__dfxtp_1 _187_ (
    .CLK(clk),
    .D(mosi),
    .Q(mosi_q)
  );
  sky130_fd_sc_hd__dfxtp_1 _188_ (
    .CLK(clk),
    .D(ss),
    .Q(ss_q)
  );
  sky130_fd_sc_hd__dfxtp_1 _189_ (
    .CLK(clk),
    .D(sck),
    .Q(sck_q)
  );
  sky130_fd_sc_hd__dfxtp_1 _190_ (
    .CLK(clk),
    .D(sck_q),
    .Q(sck_old_q)
  );
  sky130_fd_sc_hd__edfxtp_1 _191_ (
    .CLK(clk),
    .D(data_d[0]),
    .DE(_001_),
    .Q(data_q[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _192_ (
    .CLK(clk),
    .D(data_d[1]),
    .DE(_001_),
    .Q(data_q[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _193_ (
    .CLK(clk),
    .D(data_d[2]),
    .DE(_001_),
    .Q(data_q[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _194_ (
    .CLK(clk),
    .D(data_d[3]),
    .DE(_001_),
    .Q(data_q[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _195_ (
    .CLK(clk),
    .D(data_d[4]),
    .DE(_001_),
    .Q(data_q[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _196_ (
    .CLK(clk),
    .D(data_d[5]),
    .DE(_001_),
    .Q(data_q[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _197_ (
    .CLK(clk),
    .D(data_d[6]),
    .DE(_001_),
    .Q(data_q[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _198_ (
    .CLK(clk),
    .D(data_d[7]),
    .DE(_001_),
    .Q(data_q[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _199_ (
    .CLK(clk),
    .D(_111_),
    .Q(bit_ct_q[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _200_ (
    .CLK(clk),
    .D(_113_),
    .Q(bit_ct_q[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _201_ (
    .CLK(clk),
    .D(_115_),
    .Q(bit_ct_q[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _202_ (
    .CLK(clk),
    .D(_117_),
    .Q(dout_q[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _203_ (
    .CLK(clk),
    .D(_119_),
    .Q(dout_q[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _204_ (
    .CLK(clk),
    .D(_121_),
    .Q(dout_q[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _205_ (
    .CLK(clk),
    .D(_123_),
    .Q(dout_q[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _206_ (
    .CLK(clk),
    .D(_125_),
    .Q(dout_q[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _207_ (
    .CLK(clk),
    .D(_127_),
    .Q(dout_q[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _208_ (
    .CLK(clk),
    .D(_129_),
    .Q(dout_q[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _209_ (
    .CLK(clk),
    .D(_131_),
    .Q(dout_q[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _210_ (
    .CLK(clk),
    .D(_133_),
    .Q(miso_q)
  );
  assign _107_[2:1] = bit_ct_q[2:1];
  assign _108_[0] = _107_[0];
  assign done = done_q;
  assign dout = dout_q;
  assign miso = miso_q;
  assign miso_d = data_q[7];
  assign mosi_d = mosi;
  assign sck_d = sck;
  assign sck_old_d = sck_q;
  assign ss_d = ss;
  assign _071_ = miso_q;
  assign _054_ = data_q[7];
  assign _070_ = dout_q[7];
  assign _053_ = data_q[6];
  assign _069_ = dout_q[6];
  assign _052_ = data_q[5];
  assign _068_ = dout_q[5];
  assign _051_ = data_q[4];
  assign _067_ = dout_q[4];
  assign _050_ = data_q[3];
  assign _066_ = dout_q[3];
  assign _049_ = data_q[2];
  assign _065_ = dout_q[2];
  assign _048_ = data_q[1];
  assign _064_ = dout_q[1];
  assign _047_ = data_q[0];
  assign _063_ = dout_q[0];
  assign _072_ = mosi_q;
  assign _038_ = bit_ct_q[2];
  assign _037_ = bit_ct_q[1];
  assign _036_ = bit_ct_q[0];
  assign _105_ = sck_q;
  assign _104_ = sck_old_q;
  assign _106_ = ss_q;
  assign _001_ = _022_;
  assign _103_ = rst;
  assign _055_ = din[0];
  assign data_d[0] = _039_;
  assign _056_ = din[1];
  assign data_d[1] = _040_;
  assign _057_ = din[2];
  assign data_d[2] = _041_;
  assign _058_ = din[3];
  assign data_d[3] = _042_;
  assign _059_ = din[4];
  assign data_d[4] = _043_;
  assign _060_ = din[5];
  assign data_d[5] = _044_;
  assign _061_ = din[6];
  assign data_d[6] = _045_;
  assign _062_ = din[7];
  assign data_d[7] = _046_;
  assign _109_ = _023_;
  assign _111_ = _024_;
  assign _113_ = _025_;
  assign _115_ = _026_;
  assign _117_ = _027_;
  assign _119_ = _028_;
  assign _121_ = _029_;
  assign _123_ = _030_;
  assign _125_ = _031_;
  assign _127_ = _032_;
  assign _129_ = _033_;
  assign _131_ = _034_;
  assign _133_ = _035_;
endmodule
